################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
  # Insecure API access
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    swarmMode: true
################################################################
# Access logs configuration
################################################################
accessLog:
  format: common
################################################################
# Traefik Logging
################################################################
log:
  level: INFO
################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"

################################################################
# TLS
################################################################
# Let's Encrypt challenge
certificatesResolvers:
  autoresolver:
    acme:
      email: info@minimalgap.com
      storage: acme.json
      tlschallenge: true
      # httpChallenge:
      #   entryPoint: web
